#!/usr/bin/env node
/*
 * The provider matrix, written from recorded results - never by hand.
 *
 *   node scripts/web-report.mjs
 *
 * Reads:
 *   docs/testing/results/fixture-results.json   written by a full run of
 *                                                local-agent/test/run-web.cjs
 *   docs/testing/results/live-results.json      written by
 *                                                `closeni webtest <provider>`
 * Writes:
 *   docs/testing/provider-matrix.md
 *
 * Each cell is "fixture / live". The fixture half says whether the layer
 * handles that behaviour when a page does it; the live half says what happened
 * against the real site, where and when. A row that was not run is NOT_TESTED,
 * never assumed. There is deliberately no total, score or ranking: the
 * providers differ in what they expose (DeepSeek has no stop control, only
 * DeepSeek has a measured stream endpoint), and a sum would hide exactly that.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'docs/testing/results');
const read = (f) => (existsSync(f) ? JSON.parse(readFileSync(f, 'utf-8')) : null);
const fixture = read(resolve(dir, 'fixture-results.json'));
const live = read(resolve(dir, 'live-results.json')) || {};

if (!fixture) {
  console.error('no fixture results - run `node local-agent/test/run-web.cjs` (all groups) first');
  process.exit(1);
}

const PROVIDERS = [['deepseek', 'DeepSeek'], ['qwen', 'Qwen'], ['glm', 'GLM']];
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const short = (s, n = 140) => { const t = esc(s); return t.length > n ? t.slice(0, n - 1) + '…' : t; };

const fx = new Map();
const order = [];
for (const r of fixture.rows) {
  const key = r.provider + '|' + r.capability;
  fx.set(key, r);
  if (PROVIDERS.some(([id]) => id === r.provider) && !order.includes(r.capability)) order.push(r.capability);
}
const lv = new Map();
for (const [id, run] of Object.entries(live)) for (const r of run.rows || []) lv.set(id + '|' + r.capability, r);
for (const [id] of PROVIDERS) for (const [k] of lv) if (k.startsWith(id + '|') && !order.includes(k.split('|')[1])) order.push(k.split('|')[1]);

const out = [];
out.push('# Provider matrix - DeepSeek × Qwen × GLM (browser)');
out.push('');
out.push('_Generated by `node scripts/web-report.mjs` from `docs/testing/results/`. Do not edit by hand._');
out.push('');
out.push('Fixture run: ' + fixture.generatedAt + ' - ' + fixture.pass + ' checks passed, ' + fixture.fail + ' failed (Node ' + fixture.environment.node + ', ' + fixture.environment.platform + ').');
for (const [id, name] of PROVIDERS) {
  const run = live[id];
  out.push('Live ' + name + ': ' + (run ? run.at + ' on ' + run.machine + (run.state ? ' - page state ' + run.state.state : '') : 'never run'));
}
out.push('');
out.push('Each cell is **fixture / live**. Fixture rows run the same scenario against a local page shaped like that provider\'s');
out.push('(see `local-agent/test/web-fixtures/server.cjs`); they prove the automation handles the behaviour, not that the live site');
out.push('behaves that way. Live rows are the only evidence about the real sites.');
out.push('');
out.push('`PASS` handled · `FAIL` not handled · `PARTIAL` handled with a stated limit · `AUTH_REQUIRED` the site wants a login and the');
out.push('run stopped · `BLOCKED` the site could not be reached or refused automation (network policy, CAPTCHA, rate limit) ·');
out.push('`NOT_APPLICABLE` the provider has no such feature · `NOT_TESTED` not run.');
out.push('');
out.push('There is no overall score or ranking, on purpose.');
out.push('');
out.push('| Capability | ' + PROVIDERS.map(([, n]) => n).join(' | ') + ' |');
out.push('| --- | ' + PROVIDERS.map(() => '---').join(' | ') + ' |');
for (const cap of order) {
  const cells = PROVIDERS.map(([id]) => {
    const f = fx.get(id + '|' + cap);
    const l = lv.get(id + '|' + cap);
    return (f ? f.status : 'NOT_TESTED') + ' / ' + (l ? l.status : 'NOT_TESTED');
  });
  out.push('| ' + esc(cap) + ' | ' + cells.join(' | ') + ' |');
}
out.push('');

out.push('## Notes on rows that are not a plain PASS');
out.push('');
for (const [id, name] of PROVIDERS) {
  const notes = [];
  for (const cap of order) {
    const f = fx.get(id + '|' + cap);
    if (f && f.status !== 'PASS') notes.push('- fixture **' + f.status + '** ' + esc(cap) + ': ' + short(f.detail, 260));
    const l = lv.get(id + '|' + cap);
    if (l && l.status !== 'PASS') notes.push('- live **' + l.status + '** ' + esc(cap) + ': ' + short(l.detail, 260));
  }
  out.push('### ' + name);
  out.push('');
  out.push(notes.length ? notes.join('\n') : '_none_');
  out.push('');
}

for (const [group, title] of [['browser', 'Browser layer'], ['extraction', 'Extraction'], ['research', 'Research engine'], ['chaos', 'Chaos']]) {
  const rows = fixture.rows.filter((r) => r.provider === group);
  if (!rows.length) continue;
  out.push('## ' + title + ' (fixture)');
  out.push('');
  out.push('| Capability | Status | Detail |');
  out.push('| --- | --- | --- |');
  for (const r of rows) out.push('| ' + esc(r.capability) + ' | ' + r.status + ' | ' + short(r.detail, 200) + ' |');
  out.push('');
}

out.push('## Timings (fixture, milliseconds)');
out.push('');
out.push('Local pages with scripted replies, so these measure the automation\'s own overhead - opening, submitting, detecting completion,');
out.push('extracting - not model latency. The stability window in the fixture run is shortened to 1.5 s; live runs use the adapter default.');
out.push('');
const ops = [];
for (const t of fixture.timings || []) if (!ops.includes(t.op)) ops.push(t.op);
out.push('| Operation | ' + PROVIDERS.map(([, n]) => n).join(' | ') + ' |');
out.push('| --- | ' + PROVIDERS.map(() => '---:').join(' | ') + ' |');
for (const op of ops) {
  const cells = PROVIDERS.map(([id]) => {
    const t = (fixture.timings || []).find((x) => x.provider === id && x.op === op);
    return t ? String(t.ms) : '-';
  });
  if (cells.every((c) => c === '-')) continue;
  out.push('| ' + esc(op) + ' | ' + cells.join(' | ') + ' |');
}
const other = (fixture.timings || []).filter((t) => !PROVIDERS.some(([id]) => id === t.provider));
if (other.length) {
  out.push('');
  out.push('| Other | ms |');
  out.push('| --- | ---: |');
  for (const t of other) out.push('| ' + esc(t.provider + ' ' + t.op) + ' | ' + t.ms + ' |');
}
out.push('');

const liveRuns = Object.values(live);
if (liveRuns.length) {
  out.push('## Live runs');
  out.push('');
  for (const run of liveRuns) {
    out.push('- **' + run.provider + '** ' + run.at + ', ' + run.machine + ', ' + Math.round(run.durationMs / 1000) + ' s' +
      (run.state ? ' - ' + run.state.state + ': ' + short((run.state.evidence || []).join('; '), 240) : ''));
  }
  out.push('');
}

writeFileSync(resolve(root, 'docs/testing/provider-matrix.md'), out.join('\n'));
console.log('wrote docs/testing/provider-matrix.md (' + order.length + ' capabilities)');
