/**
 * How to run a project, written into the project.
 *
 * The app used to guess from filenames - main.py, index.js, Cargo.toml - so a
 * project at src/app/server.py matched nothing and the panel said "no entry
 * point found", despite the model having declared the command while planning.
 *
 * A file on disk fixes the deeper version of that: the answer survives closing
 * the app, and the project can be run without it.
 */

export const MANIFEST_NAME = "closeni.run.json";
const MANIFEST_VERSION = 1;

export interface RunManifest {
  version: number;
  run: string;
  install?: string;
  language?: string;
  /** Set when the user edits the command. Later builds then leave it alone. */
  userEdited?: boolean;
  generatedBy?: string;
}

export interface RunResolution {
  command: string | null;
  source: "manifest" | "plan" | "detected" | "none";
}

function clean(value: string | null | undefined): string {
  return (value || "").trim();
}

/**
 * Which command to run, and where it came from.
 *
 * The source is returned as well as the command because the panel shows it:
 * "from your plan" and "detected from main.py" are different levels of
 * confidence, and the user should be able to tell which one they have.
 */
export function resolveRun(
  manifest: RunManifest | null,
  planRunCommand: string | undefined,
  detected: string | null,
): RunResolution {
  const fromManifest = clean(manifest && manifest.run);
  if (fromManifest) return { command: fromManifest, source: "manifest" };
  const fromPlan = clean(planRunCommand);
  if (fromPlan) return { command: fromPlan, source: "plan" };
  const fromDetection = clean(detected);
  if (fromDetection) return { command: fromDetection, source: "detected" };
  return { command: null, source: "none" };
}

/**
 * Fold a new command into an existing manifest.
 *
 * A command the user edited is never replaced. Without that rule, correcting a
 * wrong command and then building again would silently undo the correction,
 * which is how people stop trusting a tool.
 */
export function mergeManifest(
  existing: RunManifest | null,
  run: string | null,
  opts?: { userEdited?: boolean; language?: string; install?: string },
): RunManifest {
  const o = opts || {};
  const keepUserRun = !!(existing && existing.userEdited) && !o.userEdited;
  const next: RunManifest = {
    version: MANIFEST_VERSION,
    run: keepUserRun ? existing!.run : clean(run) || clean(existing && existing.run),
    generatedBy: "CloseNI",
  };
  if (o.userEdited || (existing && existing.userEdited)) next.userEdited = true;
  const install = o.install || (existing && existing.install);
  if (install) next.install = install;
  const language = o.language || (existing && existing.language);
  if (language) next.language = language;
  return next;
}

/**
 * The script written beside the manifest, so the project runs without this app.
 *
 * The command is emitted verbatim. Quoting or escaping it would mangle
 * something like python3 -c "print(1)" into a script that fails for a reason
 * nobody could see.
 */
export function renderRunScript(manifest: RunManifest, platform: "win32" | "posix"): string {
  const install = clean(manifest.install);
  const run = clean(manifest.run);
  const lines: (string | null)[] = platform === "win32"
    ? ["@echo off", "REM Generated by CloseNI. Edit the command in the app, or here.", install || null, run, ""]
    : ["#!/bin/sh", "# Generated by CloseNI. Edit the command in the app, or here.", "set -e", install || null, run, ""];
  return lines.filter((l) => l !== null).join(platform === "win32" ? "\r\n" : "\n");
}
